// Autogenerated from Pigeon (v26.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum PlaybackStatus: Int {
  case playing = 0
  case paused = 1
  case finished = 2
  case error = 3
  case preparing = 4
}

enum BoxFitMode: Int {
  case fill = 0
  case fit = 1
}

enum TrackType: Int {
  case audio = 0
  case video = 1
  case subtitle = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoTextureData: Hashable {
  var textureId: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var fit: BoxFitMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoTextureData? {
    let textureId: Int64? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let height: Int64? = nilOrValue(pigeonVar_list[2])
    let fit: BoxFitMode? = nilOrValue(pigeonVar_list[3])

    return VideoTextureData(
      textureId: textureId,
      width: width,
      height: height,
      fit: fit
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      width,
      height,
      fit,
    ]
  }
  static func == (lhs: VideoTextureData, rhs: VideoTextureData) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Media: Hashable {
  /// The Dash URL of the media (required)
  var url: String
  /// Widevine License URL if the media is DRM protected
  var drmLicenseUrl: String? = nil
  /// Where to start media from (in seconds)
  var startFromSecond: Int64? = nil
  /// Player headers
  var headers: [String: String]? = nil
  /// IMA Ads
  var imaTagUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Media? {
    let url = pigeonVar_list[0] as! String
    let drmLicenseUrl: String? = nilOrValue(pigeonVar_list[1])
    let startFromSecond: Int64? = nilOrValue(pigeonVar_list[2])
    let headers: [String: String]? = nilOrValue(pigeonVar_list[3])
    let imaTagUrl: String? = nilOrValue(pigeonVar_list[4])

    return Media(
      url: url,
      drmLicenseUrl: drmLicenseUrl,
      startFromSecond: startFromSecond,
      headers: headers,
      imaTagUrl: imaTagUrl
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      drmLicenseUrl,
      startFromSecond,
      headers,
      imaTagUrl,
    ]
  }
  static func == (lhs: Media, rhs: Media) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlayerConfiguration: Hashable {
  var bufferingConfig: BufferingConfig? = nil
  var seekConfig: SeekConfig? = nil
  var initializeIMA: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlayerConfiguration? {
    let bufferingConfig: BufferingConfig? = nilOrValue(pigeonVar_list[0])
    let seekConfig: SeekConfig? = nilOrValue(pigeonVar_list[1])
    let initializeIMA: Bool? = nilOrValue(pigeonVar_list[2])

    return PlayerConfiguration(
      bufferingConfig: bufferingConfig,
      seekConfig: seekConfig,
      initializeIMA: initializeIMA
    )
  }
  func toList() -> [Any?] {
    return [
      bufferingConfig,
      seekConfig,
      initializeIMA,
    ]
  }
  static func == (lhs: PlayerConfiguration, rhs: PlayerConfiguration) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BufferingConfig: Hashable {
  var minBufferMs: Int64? = nil
  var maxBufferMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BufferingConfig? {
    let minBufferMs: Int64? = nilOrValue(pigeonVar_list[0])
    let maxBufferMs: Int64? = nilOrValue(pigeonVar_list[1])

    return BufferingConfig(
      minBufferMs: minBufferMs,
      maxBufferMs: maxBufferMs
    )
  }
  func toList() -> [Any?] {
    return [
      minBufferMs,
      maxBufferMs,
    ]
  }
  static func == (lhs: BufferingConfig, rhs: BufferingConfig) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SeekConfig: Hashable {
  var seekForwardMs: Int64? = nil
  var seekBackMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SeekConfig? {
    let seekForwardMs: Int64? = nilOrValue(pigeonVar_list[0])
    let seekBackMs: Int64? = nilOrValue(pigeonVar_list[1])

    return SeekConfig(
      seekForwardMs: seekForwardMs,
      seekBackMs: seekBackMs
    )
  }
  func toList() -> [Any?] {
    return [
      seekForwardMs,
      seekBackMs,
    ]
  }
  static func == (lhs: SeekConfig, rhs: SeekConfig) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrackData: Hashable {
  var id: String? = nil
  var type: TrackType? = nil
  var language: String? = nil
  var label: String? = nil
  var bitrate: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackData? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let type: TrackType? = nilOrValue(pigeonVar_list[1])
    let language: String? = nilOrValue(pigeonVar_list[2])
    let label: String? = nilOrValue(pigeonVar_list[3])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[4])
    let width: Int64? = nilOrValue(pigeonVar_list[5])
    let height: Int64? = nilOrValue(pigeonVar_list[6])

    return TrackData(
      id: id,
      type: type,
      language: language,
      label: label,
      bitrate: bitrate,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      language,
      label,
      bitrate,
      width,
      height,
    ]
  }
  static func == (lhs: TrackData, rhs: TrackData) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlaybackStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BoxFitMode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TrackType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return VideoTextureData.fromList(self.readValue() as! [Any?])
    case 133:
      return Media.fromList(self.readValue() as! [Any?])
    case 134:
      return PlayerConfiguration.fromList(self.readValue() as! [Any?])
    case 135:
      return BufferingConfig.fromList(self.readValue() as! [Any?])
    case 136:
      return SeekConfig.fromList(self.readValue() as! [Any?])
    case 137:
      return TrackData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlaybackStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BoxFitMode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? TrackType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoTextureData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? Media {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlayerConfiguration {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BufferingConfig {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? SeekConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? TrackData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}

/// Run the following to generate pigeon
/// dart run pigeon --input pigeons/pigeon.dart
/// TODO Don't depend on these directly, remove constructor
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlayerInstance {
  func create(id: String) throws
  func dispose(id: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlayerInstanceSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `PlayerInstance` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlayerInstance?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerInstance.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.create(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerInstance.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.dispose(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlayerControllerApi {
  func initialize(configuration: PlayerConfiguration?) throws
  /// Must be called if ViewMode is texture in android. Returns textureId,width,height
  func initAndroidTextureView() throws -> VideoTextureData
  func play(media: Media) throws
  func stop() throws
  func pause() throws
  func resume() throws
  func seekTo(positionMs: Int64) throws
  func seekForward() throws
  func seekBack() throws
  func dispose() throws
  func enterPiPMode() throws
  func getProgressSecond() throws -> Int64
  func getTracks() throws -> [TrackData]
  func getPlaybackStatus() throws -> PlaybackStatus
  func getPlaybackSpeed() throws -> Double
  func setPlaybackSpeed(speed: Double) throws
  func getFit() throws -> BoxFitMode
  func setFit(fit: BoxFitMode) throws
  func isPlayingIMA() throws -> Bool
  func setTrackPreference(track: TrackData?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlayerControllerApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `PlayerControllerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlayerControllerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg: PlayerConfiguration? = nilOrValue(args[0])
        do {
          try api.initialize(configuration: configurationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Must be called if ViewMode is texture in android. Returns textureId,width,height
    let initAndroidTextureViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.initAndroidTextureView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initAndroidTextureViewChannel.setMessageHandler { _, reply in
        do {
          let result = try api.initAndroidTextureView()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initAndroidTextureViewChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaArg = args[0] as! Media
        do {
          try api.play(media: mediaArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.resume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { _, reply in
        do {
          try api.resume()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionMsArg = args[0] as! Int64
        do {
          try api.seekTo(positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    let seekForwardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekForward\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekForwardChannel.setMessageHandler { _, reply in
        do {
          try api.seekForward()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekForwardChannel.setMessageHandler(nil)
    }
    let seekBackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekBack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekBackChannel.setMessageHandler { _, reply in
        do {
          try api.seekBack()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekBackChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let enterPiPModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.enterPiPMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enterPiPModeChannel.setMessageHandler { _, reply in
        do {
          try api.enterPiPMode()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enterPiPModeChannel.setMessageHandler(nil)
    }
    let getProgressSecondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.getProgressSecond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProgressSecondChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getProgressSecond()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getProgressSecondChannel.setMessageHandler(nil)
    }
    let getTracksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.getTracks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTracksChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTracks()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTracksChannel.setMessageHandler(nil)
    }
    let getPlaybackStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.getPlaybackStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlaybackStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlaybackStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlaybackStatusChannel.setMessageHandler(nil)
    }
    let getPlaybackSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.getPlaybackSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlaybackSpeedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlaybackSpeed()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlaybackSpeedChannel.setMessageHandler(nil)
    }
    let setPlaybackSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.setPlaybackSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlaybackSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speedArg = args[0] as! Double
        do {
          try api.setPlaybackSpeed(speed: speedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlaybackSpeedChannel.setMessageHandler(nil)
    }
    let getFitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.getFit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFitChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFit()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFitChannel.setMessageHandler(nil)
    }
    let setFitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.setFit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fitArg = args[0] as! BoxFitMode
        do {
          try api.setFit(fit: fitArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFitChannel.setMessageHandler(nil)
    }
    let isPlayingIMAChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.isPlayingIMA\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPlayingIMAChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPlayingIMA()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPlayingIMAChannel.setMessageHandler(nil)
    }
    let setTrackPreferenceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kvideo.PlayerControllerApi.setTrackPreference\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTrackPreferenceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let trackArg: TrackData? = nilOrValue(args[0])
        do {
          try api.setTrackPreference(track: trackArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTrackPreferenceChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PlayerEventListenerProtocol {
  func onVideoSizeUpdate(width widthArg: Int64, height heightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDurationUpdate(durationSecond durationSecondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onProgressUpdate(second secondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBufferUpdate(second secondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlaybackUpdate(status statusArg: PlaybackStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlaybackError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onIMAStatusChange(showingAd showingAdArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTracksLoaded(tracks tracksArg: [TrackData], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlaybackSpeedUpdate(speed speedArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PlayerEventListener: PlayerEventListenerProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  func onVideoSizeUpdate(width widthArg: Int64, height heightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onVideoSizeUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([widthArg, heightArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDurationUpdate(durationSecond durationSecondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onDurationUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([durationSecondArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onProgressUpdate(second secondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onProgressUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([secondArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBufferUpdate(second secondArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onBufferUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([secondArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPlaybackUpdate(status statusArg: PlaybackStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onPlaybackUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPlaybackError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onPlaybackError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onIMAStatusChange(showingAd showingAdArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onIMAStatusChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([showingAdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onTracksLoaded(tracks tracksArg: [TrackData], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onTracksLoaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tracksArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPlaybackSpeedUpdate(speed speedArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.kvideo.PlayerEventListener.onPlaybackSpeedUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([speedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
