buildscript {
    ext.kotlin_version = "2.3.20"
    ext.exo_version = "1.10.1"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:9.1.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}


apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "dev.khaled.kvideo"

    compileSdk = flutter.compileSdkVersion


    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 24
    }

    dependencies {
        implementation("androidx.media3:media3-exoplayer:$exo_version")
        implementation("androidx.media3:media3-ui:$exo_version")
        implementation("androidx.media3:media3-exoplayer-hls:$exo_version")
        implementation("androidx.media3:media3-exoplayer-dash:$exo_version")
        implementation("androidx.media3:media3-exoplayer-ima:$exo_version")
    }

}
