import com.android.Version
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

buildscript {
    ext.exo_version = "1.10.1"

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:9.2.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}


apply plugin: "com.android.library"
def agpMajor = Version.ANDROID_GRADLE_PLUGIN_VERSION.tokenize('.')[0] as int
if (agpMajor < 9) {
    apply plugin: 'kotlin-android'
}


android {
    namespace = "dev.khaled.kvideo"

    compileSdk = flutter.compileSdkVersion


    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 24
    }

    dependencies {
        implementation("androidx.media3:media3-exoplayer:$exo_version")
        implementation("androidx.media3:media3-ui:$exo_version")
        implementation("androidx.media3:media3-exoplayer-hls:$exo_version")
        implementation("androidx.media3:media3-exoplayer-dash:$exo_version")
        implementation("androidx.media3:media3-exoplayer-ima:$exo_version")
    }

}
