// Autogenerated from Pigeon (v26.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class PlaybackStatus(val raw: Int) {
  PLAYING(0),
  PAUSED(1),
  FINISHED(2),
  ERROR(3),
  PREPARING(4);

  companion object {
    fun ofRaw(raw: Int): PlaybackStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Media (
  /** The Dash URL of the media (required) */
  val url: String,
  /** Widevine License URL if the media is DRM protected */
  val drmLicenseUrl: String? = null,
  /** Where to start media from (in seconds) */
  val startFromSecond: Long? = null,
  /** Player headers */
  val headers: Map<String, String>? = null,
  /** IMA Ads */
  val imaTagUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Media {
      val url = pigeonVar_list[0] as String
      val drmLicenseUrl = pigeonVar_list[1] as String?
      val startFromSecond = pigeonVar_list[2] as Long?
      val headers = pigeonVar_list[3] as Map<String, String>?
      val imaTagUrl = pigeonVar_list[4] as String?
      return Media(url, drmLicenseUrl, startFromSecond, headers, imaTagUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      drmLicenseUrl,
      startFromSecond,
      headers,
      imaTagUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Media) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlayerConfiguration (
  val bufferingConfig: BufferingConfig? = null,
  val seekConfig: SeekConfig? = null,
  val initializeIMA: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlayerConfiguration {
      val bufferingConfig = pigeonVar_list[0] as BufferingConfig?
      val seekConfig = pigeonVar_list[1] as SeekConfig?
      val initializeIMA = pigeonVar_list[2] as Boolean?
      return PlayerConfiguration(bufferingConfig, seekConfig, initializeIMA)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bufferingConfig,
      seekConfig,
      initializeIMA,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlayerConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BufferingConfig (
  val minBufferMs: Long? = null,
  val maxBufferMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BufferingConfig {
      val minBufferMs = pigeonVar_list[0] as Long?
      val maxBufferMs = pigeonVar_list[1] as Long?
      return BufferingConfig(minBufferMs, maxBufferMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      minBufferMs,
      maxBufferMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BufferingConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SeekConfig (
  val seekForwardMs: Long? = null,
  val seekBackMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SeekConfig {
      val seekForwardMs = pigeonVar_list[0] as Long?
      val seekBackMs = pigeonVar_list[1] as Long?
      return SeekConfig(seekForwardMs, seekBackMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      seekForwardMs,
      seekBackMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SeekConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlaybackStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Media.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlayerConfiguration.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BufferingConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SeekConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlaybackStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is Media -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PlayerConfiguration -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BufferingConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SeekConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Run the following to generate pigeon
 * dart run pigeon --input pigeons/pigeon.dart
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PlayerInstance {
  fun create(id: String)
  fun dispose(id: String)

  companion object {
    /** The codec used by PlayerInstance. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `PlayerInstance` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlayerInstance?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerInstance.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.create(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerInstance.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.dispose(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlayerControllerApi {
  fun init(configuration: PlayerConfiguration?)
  /** Must be called if ViewMode is texture in android. Returns textureId,width,height */
  fun initAndroidTextureView(): Map<String, Double>
  fun play(media: Media)
  fun pause()
  fun resume()
  fun seekTo(positionMs: Long)
  fun seekForward()
  fun seekBack()
  fun dispose()
  fun enterPiPMode()

  companion object {
    /** The codec used by PlayerControllerApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `PlayerControllerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlayerControllerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.init$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as PlayerConfiguration?
            val wrapped: List<Any?> = try {
              api.init(configurationArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.initAndroidTextureView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.initAndroidTextureView())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaArg = args[0] as Media
            val wrapped: List<Any?> = try {
              api.play(mediaArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resume()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekForward$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.seekForward()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.seekBack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.seekBack()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kvideo.PlayerControllerApi.enterPiPMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.enterPiPMode()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PlayerEventListener(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PlayerEventListener. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
  }
  fun videoSizeUpdate(heightArg: Long, widthArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.videoSizeUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(heightArg, widthArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun durationUpdate(durationSecondArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.durationUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(durationSecondArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun progressUpdate(secondArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.progressUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(secondArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun bufferUpdate(secondArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.bufferUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(secondArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun playbackStatusUpdate(statusArg: PlaybackStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.playbackStatusUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPlaybackError(errorArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.onPlaybackError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onIMAStatusChange(showingAdArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.kvideo.PlayerEventListener.onIMAStatusChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(showingAdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
